version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    ports:
      - 9082:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
      ME_CONFIG_MONGODB_URL: mongodb://root:passwd@mongo:27017/
  api:
    restart: always
    build:
      context: ./persons-system
      dockerfile: prod.Dockerfile
    ports:
      - '8185:3000' 
    depends_on:
      - mongo 
    environment:
      - DATABASE_URI=mongodb://root:passwd@mongo:27017/persons?authSource=admin
      - JWT_SECRET=ac8e585b-97eb-48d3-91a3-e07c46f37b80
  frontend:
    build:
      context: ./persons-frontend/
      dockerfile: prod.Dockerfile
      args:
        - API_URL=http://localhost:8185
    ports:
      - 8184:80
    depends_on:
      - api
  webserver:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80         